
language: objective-c
compiler: clang
osx_image: xcode7.2
sudo: truev
matrix:
  include:
    - os: osx
      compiler: clang
      env: TARGET="osx"
    - os: osx
      compiler: clang
      env: TARGET="ios"
script:
    - travis/$TARGET/build.sh
git:
    depth: 10
